version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"