# Generated by Django 4.0 on 2022-02-04 01:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_date_alter_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 20, 28, 42, 607734, tzinfo=utc)),
        ),
    ]
