# Generated by Django 4.0 on 2022-02-14 00:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_post_likes_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 19, 36, 38, 602089, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=0, to=settings.AUTH_USER_MODEL, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
